baseURL: "https://knowledgebase.argyle.jp/"
languageCode: "ja"
title: "Argyle Knowledge Base"
disableKinds:
  - taxonomy
  - term

sitemap:
  filename: "sitemap.xml"
  changefreq: "monthly"
  priority: 0.5

markup:
  goldmark:
    renderer:
      unsafe: false

outputs:
  home:
    - HTML
  page:
    - HTML
